<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/linkstorage">
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
</head>

<body>
    <header>
        <h1>Test header</h1>
    </header>

    <nav>
        <h2>Menu here will be</h2>
    </nav>
    <br>

    <?php
        $this->controller->renderView();
    ?>

    <footer>
        <p>Test footer</p>
    </footer>
</body>
</html>