
<h1>Форма регистрации</h1>
<form action="register.php" method="post">
    <input type="text" name="login" placeholder="Login" required>
    <input type="text" name="firstName" placeholder="First Name" required>
    <input type="text" name="lastName" placeholder="Last Name" required>
    <input type="email" name="email" placeholder="Email" required>
    <input id="password" type="password" name="password" placeholder="Password" minlength="8" required>
    <input id="confirm_password" type="password" name="" placeholder="Repeat password" minlength="8" required>

    <button type="submit">Login</button>
</form>
<p>Back to <a href="login.php">login</a></p>
