<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title><?=$this->head["title"]?></title>
</head>
<body class="bg-light">
<header>
    <p class="bg-primary px-5 py-2 my-0 text-white">Привет, <?=$userInfo["firstName"]?></p>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-5">
        <div class="collapse navbar-collapse  justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/main-page">Main</a>
                </li>
                <?php if($loggedIn):?>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="#">My links</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="#">Users</a>
                </li>
                <?php endif;?>
            </ul>
            <ul class="navbar-nav">
                <?php if (!$loggedIn):?>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/register">Register</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                <?php else:?>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
                <?php endif;?>
            </ul>
        </div>
    </nav>
</header>
