<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title><?=$this->head["title"]?></title>
</head>
<body class="bg-light">
<header>
    <div></div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-5">
        <div class="collapse navbar-collapse  justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item mx-2 active">
                    <a class="nav-link" href="#">Main</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="#">My links</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="#">Users</a>
                </li>
            </ul>
            <div>
                <a class="nav-link btn btn-primary" href="#">Logout</a>
            </div>
        </div>
    </nav>
</header>
