
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/styles/style.css">
    <title><?=$this->head["title"]?></title>
</head>
<body class="bg-light">
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-5">
        <div class="collapse navbar-collapse  justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="/">Main</a>
                </li>
                <?php if(ServiceProvider::getService("Authorization")->isLoggedIn()):?>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="/myLinks">My links</a>
                </li>
                <?php endif; ?>
                <?php if(ServiceProvider::getService("Authentication")->canReadUsersList()):?>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="/users">Users</a>
                </li>
                <?php endif;?>
                <?php if (ServiceProvider::getService("Authorization")->isLoggedIn()):?>
                <li class="nav-item mx-2">
                    <a class="nav-link btn btn-primary" href="/link/create">Create Link</a>
                </li>
                <?php endif;?>
            </ul>
            <ul class="navbar-nav">
                <?php if (!ServiceProvider::getService("Authorization")->isLoggedIn()):?>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/register">Register</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                <?php else:?>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
                <?php endif;?>
            </ul>
        </div>
    </nav>
</header>
