<?php
    $data = ServiceProvider::getService("Data")->getData();
?>
<ul class="list-group list-group-flush">
    <?php
        $counter = 1;
        foreach($data["links"] as $link) :?>
    <?php
        if ($counter%2 == 0) {
            $listGroupItem = "list-group-item-info";
        }
        else {
            $listGroupItem = "list-group-item-primary";
        }
        $counter ++;
    ?>
    <li class="link-element list-group-item list-group-item-action <?=$listGroupItem?> px-5 py-3" id='link-<?=$link["id"]?>'>
        <a href='/link/read/<?=$link["id"]?>'>
            <h4>
                <?php
                    if ($link["private"]) $privacyImageClass="d-inline";
                    else $privacyImageClass="d-none"
                ?>
                <img class="linkPrivate <?=$privacyImageClass;?>" src="/images/baseline-assignment_ind-24px.svg" alt="private">
                <span class="linkTitle"><?=$link["title"]?></span>
            </h4>
        </a>
        <p class="linkUrl">
        <?php
            if (strlen($link["url"])>100) {
                $link["url"] = substr($link["url"], 0, 97)."...";
            }
            echo $link["url"];
        ?>
        </p>
        <p class="small">Published by
            <a href="/showList?userId=<?=$link["userId"]?>">
                <?=$link["firstName"]." ".$link["lastName"]?>
            </a>
            at <?=date("Y-m-d H:i", strtotime($link["dateCreated"]))?></p>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "edit", $link["id"])):?>
        <button type="button" class="btn btn-primary text-white btn-edit">Edit</button>
        <?php endif; ?>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "delete", $link["id"])):?>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/link/delete/<?=$link["id"]?>">
                Delete
            </button>
        <?php endif; ?>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "edit", $link["id"])):?>
        <!-- Modal for link edit-->
        <div class="row toggle-content edit-popup">
            <form class="col-3 mt-3 p-2 bg-white editLink-form" method="post">
                <h5>Edit Link <span class="close close-button" id="popup-close">&times;</span></h5>
                <input type="hidden" class="linkId" name="linkId" value="<?=$link["id"]?>">
                <input type="hidden" class="pastLinkUrl" name="pastLinkUrl" value="<?=$link["url"]?>">
                <input type="hidden" class="userId" name="userId" value="<?=$link["userId"]?>">
                <div class="form-group ">
                    <label for="linkTitle<?=$link["id"]?>">Title</label>
                    <input id="linkTitle<?=$link["id"]?>" class="linkTitle form-control" type="text" name="linkTitle" value="<?=$link["title"]?>" maxlength="100" required>
                </div>
                <div class="form-group ">
                    <label for="linkUrl<?=$link["id"]?>">Url</label>
                    <input id="linkUrl<?=$link["id"]?>" class="linkUrl form-control" type="url" name="linkUrl" value="<?=$link["url"]?>" maxlength="2083" required>
                </div>
                <div class="form-group ">
                    <label for="linkDescription<?=$link["id"]?>">Description</label>
                    <textarea id="linkDescription<?=$link["id"]?>" class="linkDescription form-control" name="linkDescription" rows="3" maxlength="3000"><?=$link["description"]?></textarea>
                </div>
                <div class="form-check mb-3">
                    <input type="checkbox" class="form-check-input linkPrivacy" id="linkPrivacy<?=$link["id"]?>" name="linkPrivacy"
                        <?php if ($link["private"] == 1) echo "checked"?>>
                    <label class="form-check-label" for="linkPrivacy<?=$link["id"]?>">Privacy</label>
                </div>
                <button class="btn btn-primary" type="submit">Edit</button>
                <div id="result" class="result mt-2"></div>
            </form>
        </div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?=$data["pagination"];?>

<!-- Modal for link delete-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this link?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="/app/scripts/editLink.js"></script>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget);
        let url = button.data('url');
        let deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>
