<?php
    $data = ServiceProvider::getService("Data")->getData();
?>
<div id="popup-background"></div>
<ul class="list-group list-group-flush">
    <?php
        $counter = 1;
        foreach($data["links"] as $link) :?>
    <?php
        if ($counter%2 == 0) {
            $listGroupItem = "list-group-item-info";
        }
        else {
            $listGroupItem = "list-group-item-primary";
        }
        $counter ++;
    ?>
    <li class="list-group-item list-group-item-action <?=$listGroupItem?> px-5" id='link-<?=$link["id"]?>'>

        <a href='/link/read/<?=$link["id"]?>'>
            <h4>
                <?php
                    if ($link["private"]) $privacyImageClass="d-inline";
                    else $privacyImageClass="d-none"
                ?>
                <img class="linkPrivate <?=$privacyImageClass;?>" src="/images/baseline-assignment_ind-24px.svg" alt="private">
                <span class="linkTitle"><?=$link["title"]?></span>
            </h4>
        </a>
        <p class="linkUrl">
        <?php
            if (strlen($link["url"])>100) {
                $link["url"] = substr($link["url"], 0, 97)."...";
            }
            echo $link["url"];
        ?>
        </p>
        <p class="small">Published by
            <a href="/showList?userId=<?=$link["userId"]?>">
                <?=$link["firstName"]." ".$link["lastName"]?>
            </a>
            at <?=date("Y-m-d H:i", strtotime($link["dateCreated"]))?></p>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "edit", $link["id"])):?>
        <button type="button" onclick="showEditPopup(<?=$link["id"]?>)" class="btn btn-primary text-white btn-edit">Edit</button>
        <?php endif; ?>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "delete", $link["id"])):?>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/link/delete/<?=$link["id"]?>">
                Delete
            </button>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?=$data["pagination"];?>
<!-- Modal for link edit-->
<div class="row d-none justify-content-center fixed-top" id="edit-popup">
    <form class="col-3 mb-3 p-2 bg-white edit-form" id="edit-form" onsubmit="editLink(); return false;" method="post">
        <h5>Edit Link <span class="close close-button" id="popup-close" onclick="hideEditPopup()">&times;</span></h5>
        <input type="hidden" id="linkId" name="linkId" value="<?=$data["linkId"]?>">
        <input type="hidden" id="pastLinkUrl" name="pastLinkUrl" value="<?=$data["url"]?>">
        <input type="hidden" id="userId" name="userId" value="<?=$data["userId"]?>">

        <div class="form-group ">
            <label for="linkTitle">Title</label>
            <input id="linkTitle" class="form-control" type="text" name="linkTitle" value="<?=$data["title"]?>" maxlength="100" required>
        </div>
        <div class="form-group ">
            <label for="linkUrl">Url</label>
            <input id="linkUrl" class="form-control" type="url" name="linkUrl" value="<?=$data["url"]?>" maxlength="2083" required>
        </div>
        <div class="form-group ">
            <label for="linkDescription">Description</label>
            <textarea id="linkDescription" class="form-control" name="linkDescription" rows="3" maxlength="3000"><?=$data["description"]?></textarea>
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="linkPrivacy" name="linkPrivacy"
                <?php if ($data["private"] == 1) echo "checked"?>>
            <label class="form-check-label" for="linkPrivacy">Privacy</label>
        </div>
        <button class="btn btn-primary" type="submit">Edit</button>
        <div id="result" class="mt-2"></div>
    </form>
</div>


<!-- Modal for link delete-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this link?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    function showEditPopup(link) {
        let editPopup = document.getElementById("edit-popup");
        let popupBackground = document.getElementById("popup-background");
        let message = document.getElementById("result");
        message.innerText = "";
        popupBackground.style.display = "block";
        editPopup.classList.remove("d-none");
        editPopup.classList.add("d-flex");
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                let result = JSON.parse(this.response);
                document.getElementById("linkId").value = result.id;
                document.getElementById("pastLinkUrl").value = result.url;
                document.getElementById("userId").value = result.userId;
                document.getElementById("linkTitle").value = result.title;
                document.getElementById("linkUrl").value = result.url;
                document.getElementById("linkDescription").value = result.description;
                if (result.private == 1) {
                    document.getElementById("linkPrivacy").checked = true;
                }
                else {
                    document.getElementById("linkPrivacy").checked = false;
                }
            }
        };
        xhttp.open("GET", "link/readAjax?linkId="+link, true);
        xhttp.send();
    }

    function hideEditPopup() {
        let editPopup = document.getElementById("edit-popup");
        let popupBackground = document.getElementById("popup-background");
        editPopup.classList.remove("d-flex");
        editPopup.classList.add("d-none");
        popupBackground.style.display = "none";
    }

    function editLink() {
        let form = document.getElementById("edit-form");
        let request = new XMLHttpRequest();
        let formData = new FormData(form);
        request.open("POST", "link/editAjax");
        request.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                let result = JSON.parse(this.response);
                let message = document.getElementById("result");
                if (result.edited==="ok") {
                    let linkId = document.getElementById("linkId").value;
                    let linkTitle = document.getElementById("linkTitle").value;
                    let linkUrl = document.getElementById("linkUrl").value;
                    let linkPrivacy = document.getElementById("linkPrivacy").checked;
                    let link = document.getElementById("link-" + linkId);
                    link.getElementsByClassName("linkTitle")[0].innerHTML = linkTitle;
                    link.getElementsByClassName("linkUrl")[0].innerHTML = linkUrl;
                    if(linkPrivacy) {
                        link.getElementsByClassName("linkPrivate")[0].classList.remove("d-none");
                        link.getElementsByClassName("linkPrivate")[0].classList.add("d-inline");
                    }
                    else {
                        link.getElementsByClassName("linkPrivate")[0].classList.remove("d-inline");
                        link.getElementsByClassName("linkPrivate")[0].classList.add("d-none");
                    }
                    hideEditPopup();
                }
                message.innerText = result.message;
            }
        };
        request.send(formData);
    }

    $('#deleteModal').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget);
        let url = button.data('url');
        let deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>
