
<?php
    $data = ServiceProvider::getService("Data")->getData()["linkInfo"];
    $error = ServiceProvider::getService("Data")->getData()["errorMessage"];
    $userData = ServiceProvider::getService("Authentication")->getUserInfo();
?>
<div class="editLinkPage px-5 py-4 col-md-4">
    <form class="mb-3" method="post">
        <input type="hidden" name="userId" value="<?=$userData["id"]?>">
        <div class="form-group ">
            <label for="linkTitle">Title</label>
            <input id="linkTitle" class="form-control" type="text" name="linkTitle" value="<?=$data["title"]?>" maxlength="100" required >
        </div>
        <div class="form-group ">
            <label for="linkUrl">Url</label>
            <input id="linkUrl" class="form-control" type="url" name="linkUrl" value="<?=$data["url"]?>" maxlength="2083" required>
        </div>
        <div class="form-group ">
            <label for="linkDescription">Description</label>
            <textarea id="linkDescription" class="form-control" name="linkDescription" rows="3" maxlength="3000" ><?=$data["description"]?></textarea>
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="privacy" name="linkPrivacy"
                <?php if ($data["private"] == 1) echo "checked"?>>
            <label class="form-check-label" for="privacy">Privacy</label>
        </div>
        <button class="btn btn-primary" type="submit">Create Link</button>
    </form>
    <?php if ($error!=""): ?>
        <div class="alert alert-danger" role="alert">
            <?=$error?>
        </div>
    <?php endif; ?>
</div>