
<?php
    $data = ServiceProvider::getService("Data")->getData()["linkInfo"];
    $error = ServiceProvider::getService("Data")->getData()["errorMessage"];
?>
<div class="editLinkPage px-5 py-4 col-md-4">
    <form class="mb-3" method="post">
        <input type="hidden" name="linkId" value="<?=$data["linkId"]?>">
        <input type="hidden" name="pastLinkUrl" value="<?=$data["url"]?>">
        <input type="hidden" name="userId" value="<?=$data["userId"]?>">
        <div class="form-group ">
            <label for="linkTitle">Title</label>
            <input id="linkTitle" class="form-control" type="text" name="linkTitle" value="<?=$data["title"]?>" maxlength="100" required>
        </div>
        <div class="form-group ">
            <label for="linkUrl">Url</label>
            <input id="linkUrl" class="form-control" type="url" name="linkUrl" value="<?=$data["url"]?>" maxlength="2083" required>
        </div>
        <div class="form-group ">
            <label for="linkDescription">Description</label>
            <textarea id="linkDescription" class="form-control" name="linkDescription" rows="3" maxlength="3000"><?=$data["description"]?></textarea>
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="privacy" name="linkPrivacy"
            <?php if ($data["private"] == 1) echo "checked"?>>
            <label class="form-check-label" for="privacy">Privacy</label>
        </div>
        <button class="btn btn-primary" type="submit">Edit Link</button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/link/delete/<?=$data["linkId"]?>">
            Delete Link
        </button>
    </form>
    <?php if ($error!=""): ?>
        <div class="alert alert-danger" role="alert">
            <?=$error?>
        </div>
    <?php endif; ?>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this link?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var url = button.data('url');
        var deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>