<div class="loginPage px-5 py-4 col-md-4">
    <h2>Login</h2>
    <form class="mb-3" action="/login" method="post">
        <div class="form-group ">
            <label for="login">Login</label>
            <input id="login" class="form-control" type="text" name="login" placeholder="" required>
        </div>
        <div class="form-group ">
            <label for="password">Password</label>
            <input id="password" class="form-control" type="text" name="password" placeholder="" required>
        </div>
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <?php if ($errorMessage): ?>
    <div class="alert alert-danger" role="alert"><?=$errorMessage?></div>
    <?php endif; ?>
    <?php if ($successMessage): ?>
        <div class="alert alert-success" role="alert"><?=$successMessage?></div>
    <?php endif; ?>
</div>
