<?php
    $data = ServiceProvider::getService("Data")->getData();
?>
<ul class="list-group list-group-flush">
    <?php
        $counter = 1;
        foreach($data["links"] as $link) :?>
    <?php
        if ($counter%2 == 0) {
            $listGroupItem = "list-group-item-info";
        }
        else {
            $listGroupItem = "list-group-item-primary";
        }
        $counter ++;
    ?>
    <li class="list-group-item list-group-item-action <?=$listGroupItem?> px-5">

        <a href='/link/read/<?=$link["id"]?>'>
            <h4>
                <?php if ($link["private"]):?>
                <img src="/images/baseline-assignment_ind-24px.svg">
                <?php endif;?>
                <?=$link["title"]?>
            </h4>
        </a>
        <p>
        <?php
            if (strlen($link["url"])>100) {
                $link["url"] = substr($link["url"], 0, 97)."...";
            }
            echo $link["url"];
        ?>
        </p>
        <?php if (ServiceProvider::getService("Authentication")->canEditThisLink($link["id"])):?>
        <a href="/link/edit/<?=$link["id"]?>" class="btn btn-primary text-white">Edit</a>
        <?php endif; ?>
        <?php if (ServiceProvider::getService("Authentication")->canDeleteThisLink($link["id"])):?>
        <a href="/link/delete/<?=$link["id"]?>" class="btn btn-primary text-white">Delete</a>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?=$data["pagination"];?>
<!--<nav>
    <ul class="pagination  mt-4 px-5">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
-->