<?php
    $data = ServiceProvider::getService("Data")->getData();
?>
<ul class="list-group list-group-flush">
    <?php
        $counter = 1;
        foreach($data["links"] as $link) :?>
    <?php
        if ($counter%2 == 0) {
            $listGroupItem = "list-group-item-info";
        }
        else {
            $listGroupItem = "list-group-item-primary";
        }
        $counter ++;
    ?>
    <li class="list-group-item list-group-item-action <?=$listGroupItem?> px-5">

        <a href='/link/read/<?=$link["id"]?>'>
            <h4>
                <?php if ($link["private"]):?>
                <img src="/images/baseline-assignment_ind-24px.svg" alt="private">
                <?php endif;?>
                <?=$link["title"]?>
            </h4>
        </a>
        <p>
        <?php
            if (strlen($link["url"])>100) {
                $link["url"] = substr($link["url"], 0, 97)."...";
            }
            echo $link["url"];
        ?>
        </p>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "edit", $link["id"])):?>
        <a href="/link/edit/<?=$link["id"]?>" class="btn btn-primary text-white">Edit</a>
        <?php endif; ?>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("link", "delete", $link["id"])):?>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/link/delete/<?=$link["id"]?>">
                Delete
            </button>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?=$data["pagination"];?>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this link?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget);
        let url = button.data('url');
        let deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>
