<div class="registerPage px-5 py-4 col-md-4">
    <h2>Registration</h2>
    <form class="mb-3" action="/register" method="post">
        <div class="form-group ">
            <label for="login">Login</label>
            <input id="login" class="form-control" type="text" name="login" placeholder="Login" required>
        </div>
        <div class="form-group ">
            <label for="login">First Name</label>
            <input id="firstName" class="form-control" type="text" name="firstName" placeholder="First Name" required>
        </div>
        <div class="form-group ">
            <label for="login">Last Name</label>
            <input id="lastName" class="form-control" type="text" name="lastName" placeholder="Last Name" required>
        </div>
        <div class="form-group ">
            <label for="login">Email</label>
            <input id="email" class="form-control" type="email" name="email" placeholder="Email" required>
        </div>
        <div class="form-group ">
            <label for="login">Password</label>
            <input id="password" class="form-control" type="text" name="password" placeholder="Password" required>
        </div>
        <div class="form-group">
            <label for="login">Confirm Password</label>
            <input id="confirm_password" class="form-control" type="text" name="" placeholder="Repeat password" required>
        </div>
        <button class="btn btn-primary" type="submit">Register</button>
    </form>

    <?php if ($error!=""): ?>
    <div class="alert alert-danger" role="alert">
        <?=$error?>
    </div>
    <?php endif; ?>

    <?php if ($success!=""): ?>
    <div class="alert alert-success" role="alert">
        <?=$success?>
    </div>
    <?php endif; ?>
</div>
<script>
    let password = document.getElementById("password");
    let confirm_password = document.getElementById("confirm_password");
    function validatePassword(){
        if(password.value !== confirm_password.value) {
            confirm_password.setCustomValidity("Passwords Don't Match");
        } else {
            confirm_password.setCustomValidity('');
        }
    }
    password.onchange = validatePassword;
    confirm_password.onchange = validatePassword;
</script>
