
<?php $data = ServiceProvider::getService("Data")->getData();?>
<div class="editLinkPage px-5 py-4 col-md-4">
    <form class="mb-3" method="post">
        <input type="hidden" name="userId" value="<?=$data["id"]?>">
        <input type="hidden" name="pastUserLogin" value="<?=$data["login"]?>">
        <div class="form-group ">
            <label for="login">Login</label>
            <input id="login" class="form-control" type="text" name="login" placeholder="Login" value="<?=$data["login"]?>" readonly>
        </div>
        <div class="form-group ">
            <label for="firstName">First Name</label>
            <input id="firstName" class="form-control" type="text" name="firstName" placeholder="First Name" value="<?=$data["firstName"]?>" required>
        </div>
        <div class="form-group ">
            <label for="lastName">Last Name</label>
            <input id="lastName" class="form-control" type="text" name="lastName" placeholder="Last Name" value="<?=$data["lastName"]?>" required>
        </div>
        <div class="form-group ">
            <label for="email">Email</label>
            <input id="email" class="form-control" type="email" name="email" placeholder="Email" value="<?=$data["email"]?>" required>
        </div>
        <div class="form-check mb-3 <?php  if (ServiceProvider::getService("AccessControl")->checkRights("user", "editOther")) echo "d-none" ?>">
            <input type="checkbox" class="form-check-input" id="approved" name="approved"
                <?php if ($data["approved"] == 1) echo "checked"?>>
            <label class="form-check-label" for="approved">Active</label>
        </div>

        <div class="form-group <?php if (ServiceProvider::getService("AccessControl")->checkRights("user", "editOther")) echo "d-none" ?>">
            <label for="role">Role</label>
            <select class="form-control" name="roleId" id="role">
                <?php foreach($data["roles"] as $role):?>
                    <?php if ($role["name"]!="anonymous"):?>
                        <option value="<?=$role["id"]?>"
                        <?php if ($role["id"] == $data["roleId"]) echo "selected"?>>
                            <?=$role["name"]?>
                        </option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group ">
            <label for="password">Password</label>
            <input id="password" class="form-control" type="text" name="password" placeholder="Password" >
        </div>
        <div class="form-group">
            <label for="confirmPassword">Confirm Password</label>
            <input id="confirmPassword" class="form-control" type="text" name="" placeholder="Repeat password" >
        </div>
        <button class="btn btn-primary" type="submit">Edit</button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/user/delete/<?=$data["id"]?>">
            Delete
        </button>
    </form>
    <?php if ($data["success"]!=""): ?>
        <div class="alert alert-success" role="alert">
            <?=$data["success"]?>
        </div>
    <?php endif; ?>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this user?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(".alert").delay(2000).fadeOut("slow");

    let password = document.getElementById("password");
    let confirm_password = document.getElementById("confirmPassword");
    function validatePassword(){
        if (password.value!="" && confirm_password.value!=""){
            if(password.value !== confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            } else {
                confirm_password.setCustomValidity('');
            }
        }
    }
    password.onchange = validatePassword;
    confirm_password.onchange = validatePassword;
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var url = button.data('url');
        var deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>
