<?php $data = ServiceProvider::getService("Data")->getData(); ?>
<ul class="list-group list-group-flush">
    <?php
    $counter = 1;
    foreach($data["users"] as $user) :?>
        <?php if (ServiceProvider::getService("AccessControl")->checkRights("user", "edit", $user["id"])):?>
            <?php
            if ($counter%2 == 0) {
                $listGroupItem = "list-group-item-info";
            }
            else {
                $listGroupItem = "list-group-item-primary";
            }
            $counter ++;
            ?>
            <li class="list-group-item list-group-item-action <?=$listGroupItem?> px-5">
                <a href='/user/edit/<?=$user["id"]?>'>
                    <h4>
                        <?=$user["login"]?>
                    </h4>
                </a>
                <p>
                    <?=$user["firstName"]." ".$user["lastName"] ?>
                </p>
                <p>
                    <?=$user["email"] ?>
                </p>
                <p>
                    <a class="btn btn-primary" href="/user/edit/<?=$user["id"]?>">Edit</a>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal" data-url="/user/delete/<?=$user["id"]?>">
                        Delete
                    </button>
                </p>
            </li>
        <?php endif;?>
    <?php endforeach; ?>
</ul>

<?=$data["pagination"];?>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm deleting user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you want to delete this user?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary delete-btn">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var url = button.data('url');
        var deleteButton = $(".delete-btn");
        deleteButton.on('click', function(){
            location.replace(url);
        });
    })
</script>
