<?php $data = ServiceProvider::getService("Data")->getData(); ?>


<ul class="list-group list-group-flush">
    <?php
    $counter = 1;
    foreach($data["users"] as $user) :?>
        <?php
        if ($counter%2 == 0) {
            $listGroupItem = "list-group-item-info";
        }
        else {
            $listGroupItem = "list-group-item-primary";
        }
        $counter ++;
        ?>
        <li class="list-group-item list-group-item-action <?=$listGroupItem?> px-5">
            <a href='/user/edit/<?=$user["id"]?>'>
                <h4>
                    <?=$user["login"]?>
                </h4>
            </a>
            <p>
                <?=$user["firstName"]." ".$user["lastName"] ?>
            </p>
            <p>
                <?=$user["email"] ?>
            </p>
        </li>
    <?php endforeach; ?>
</ul>
<?=$data["pagination"];?>