
<?php $data = ServiceProvider::getService("Data")->getData();?>
<div class="editLinkPage px-5 py-4 col-md-4">
    <form class="mb-3" method="post">
        <input type="hidden" name="userId" value="<?=$data["id"]?>">
        <input type="hidden" name="pastUserLogin" value="<?=$data["login"]?>">
        <div class="form-group ">
            <label for="login">Login</label>
            <input id="login" class="form-control" type="text" name="login" placeholder="Login" value="<?=$data["login"]?>" readonly>
        </div>
        <div class="form-group ">
            <label for="firstName">First Name</label>
            <input id="firstName" class="form-control" type="text" name="firstName" placeholder="First Name" value="<?=$data["firstName"]?>" required>
        </div>
        <div class="form-group ">
            <label for="lastName">Last Name</label>
            <input id="lastName" class="form-control" type="text" name="lastName" placeholder="Last Name" value="<?=$data["lastName"]?>" required>
        </div>
        <div class="form-group ">
            <label for="email">Email</label>
            <input id="email" class="form-control" type="email" name="email" placeholder="Email" value="<?=$data["email"]?>" required>
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="approved" name="approved"
                <?php if ($data["approved"] == 1) echo "checked"?>>
            <label class="form-check-label" for="approved">Approved</label>
        </div>
        <div class="form-group ">
            <label for="role">Role</label>
            <select class="form-control" name="roleId" id="role">
                <?php foreach($data["roles"] as $role):?>
                    <?php if ($role["name"]!="anonymous"):?>
                        <option value="<?=$role["id"]?>"
                        <?php if ($role["id"] == $data["roleId"]) echo "selected"?>>
                            <?=$role["name"]?>
                        </option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group ">
            <label for="password">Password</label>
            <input id="password" class="form-control" type="text" name="password" placeholder="Password" >
        </div>
        <div class="form-group">
            <label for="confirmPassword">Confirm Password</label>
            <input id="confirmPassword" class="form-control" type="text" name="" placeholder="Repeat password" >
        </div>
        <button class="btn btn-primary" type="submit">Edit</button>
        <a class="btn btn-primary" href="/user/delete/<?=$data["id"]?>">Delete</a>
    </form>
    <?php if ($data["errorMessage"]!=""): ?>
        <div class="alert alert-danger" role="alert">
            <?=$data["errorMessage"]?>
        </div>
    <?php endif; ?>
</div>
<script>
    let password = document.getElementById("password");
    let confirm_password = document.getElementById("confirmPassword");
    function validatePassword(){
        if (password.value!="" && confirm_password.value!=""){
            if(password.value !== confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            } else {
                confirm_password.setCustomValidity('');
            }
        }
    }
    password.onchange = validatePassword;
    confirm_password.onchange = validatePassword;
</script>